# Generated by Django 4.0.1 on 2022-05-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dept_name',
            field=models.CharField(max_length=200),
        ),
    ]
