# Generated by Django 4.0.1 on 2022-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_delete_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=150)),
                ('pic', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
                ('course_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('intake', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('long_description', models.TextField()),
            ],
        ),
    ]
