# Generated by Django 4.0.1 on 2022-05-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
                ('heading', models.CharField(max_length=200)),
            ],
        ),
    ]
