# Generated by Django 4.0.1 on 2022-05-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_noticeboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='useful_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('website_link', models.CharField(max_length=200)),
            ],
        ),
    ]
