# Generated by Django 4.0.1 on 2022-05-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_useful_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='useful_links',
            new_name='useful_link',
        ),
    ]
