# Generated by Django 4.0.1 on 2022-05-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_principal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='principal',
            new_name='principals',
        ),
    ]
