# Generated by Django 4.0.1 on 2022-05-12 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_rename_principal_principals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='principals',
            new_name='our_team',
        ),
    ]
