# Generated by Django 4.0.1 on 2022-05-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_rename_principals_our_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='our_team',
        ),
    ]
