# Generated by Django 4.0.1 on 2022-05-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_our_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_btech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('dateOf_join', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('welcome_note', models.CharField(max_length=500)),
                ('profile_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='faculty_mba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('dateOf_join', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('welcome_note', models.CharField(max_length=500)),
                ('profile_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='faculty_mca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('dateOf_join', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('welcome_note', models.CharField(max_length=500)),
                ('profile_details', models.TextField()),
            ],
        ),
    ]
