# Generated by Django 4.0.1 on 2022-05-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_faculty_basicscience'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=100)),
                ('photo1', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
                ('photo2', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
                ('photo3', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
                ('photo4', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
                ('photo5', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
                ('photo6', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
                ('photo7', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
                ('photo8', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
            ],
        ),
    ]
