# Generated by Django 4.0.1 on 2022-05-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_photo_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='departments',
        ),
    ]
