# Generated by Django 4.0.1 on 2022-05-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
