# Generated by Django 4.0.1 on 2022-05-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_university_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='mandatory_disclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
    ]
