# Generated by Django 4.0.1 on 2022-05-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_mandatory_disclosure'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('post_date', models.CharField(max_length=50)),
                ('details', models.TextField()),
            ],
        ),
    ]
