# Generated by Django 4.0.1 on 2022-05-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_latest_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='university_guidline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
