# Generated by Django 4.0.1 on 2022-05-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_university_guidline'),
    ]

    operations = [
        migrations.CreateModel(
            name='informn_corner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('pdf', models.FileField(upload_to='')),
                ('photo', models.ImageField(blank=True, default='-', null=True, upload_to='img', verbose_name='file')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
