# Generated by Django 4.0.1 on 2022-05-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_informn_corner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='informn_corner',
        ),
    ]
