# Generated by Django 4.0.1 on 2022-06-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0032_aicte_latest_eoa_aicte_previous_eoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
